[book]
title = "CE-RISE Digital Passport Engineering Assistant"
authors = ["CE-RISE consortium"]
language = "en"
src = "."

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://codeberg.org/CE-RISE-software/dp-engineering-assistant"
sidebar-header-nav = true
additional-js = ["theme/custom.js"]
